In [2]:
import snowflake.connector
import pandas as pd
import os
from dotenv import load_dotenv

In [16]:
load_dotenv("/home/scooperlosses/DB_proj/snowflake_dbt_ETL/etl_proj/.env")


con = snowflake.connector.connect(
    account=os.getenv("SHOWFLAKE_ACCOUNT"),
    user=os.getenv("SHOWFLAKE_USER"),
    password=os.getenv("SHOWFLAKE_PASSWORD"),
    database=os.getenv("DATABASE"),
    schema="SILVER",
    warehouse=os.getenv("WAREHOUSE")
)


cursor = con.cursor()
cursor.execute("SELECT * FROM CAFEDB.SILVER.int_restore_prices")
df = cursor.fetch_pandas_all()
df.head()

  TRANSACTION_ID   ITEMS  PRICE_PER_UNIT  QUANTITIES  TOTAL_SPENT
0    TXN_1961373  Coffee             2.0         2.0          4.0
1    TXN_4977031    Cake             3.0         4.0         12.0
2    TXN_4271903  Cookie             1.0         4.0          4.0
3    TXN_7034554   Salad             5.0         2.0         10.0
4    TXN_3160411  Coffee             2.0         2.0          4.0

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9324 entries, 0 to 9323
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   TRANSACTION_ID  9324 non-null   object
 1   ITEMS           9324 non-null   object
 2   PRICE_PER_UNIT  9324 non-null   float64
 3   QUANTITIES      9324 non-null   float64
 4   TOTAL_SPENT     9324 non-null   float64
dtypes: float64(3), object(2)
memory usage: 364.3+ KB

In [10]:
df['PRICE_PER_UNIT'].unique()

array(['2.0', '3.0', '1.0', '5.0', '4.0', None, '1.5'], dtype=object)

In [17]:
df[['QUANTITIES','PRICE_PER_UNIT', 'TOTAL_SPENT']]

      QUANTITIES  PRICE_PER_UNIT  TOTAL_SPENT
0            2.0             2.0          4.0
1            4.0             3.0         12.0
2            4.0             1.0          4.0
3            2.0             5.0         10.0
4            2.0             2.0          4.0
...          ...             ...          ...
9319         2.0             4.0          8.0
9320         2.0             2.0          4.0
9321         4.0             2.0          8.0
9322         3.0             1.0          3.0
9323         3.0             4.0         12.0

[9324 rows x 3 columns]

In [12]:
df.loc[df['QUANTITIES'].isnull(), ['QUANTITIES', 'PRICE_PER_UNIT', 'TOTAL_SPENT']]

     QUANTITIES PRICE_PER_UNIT TOTAL_SPENT
61         None            3.0         6.0
314        None            1.0         3.0
344        None            2.0         4.0
377        None            3.0         3.0
491        None            1.0         1.0
...         ...            ...         ...
9037       None            3.0        15.0
9233       None            5.0         5.0
9257       None            2.0     UNKNOWN
9273       None            5.0        10.0
9282       None            2.0        10.0

[130 rows x 3 columns]

In [18]:
df[df.isnull().any(axis=1)].head(10)

Empty DataFrame
Columns: [TRANSACTION_ID, ITEMS, PRICE_PER_UNIT, QUANTITIES, TOTAL_SPENT]
Index: []